name: 'Src Unit-tests'
description: 'Build from source and run unittests.'
inputs:
  python-version:
    description: 'The version of Python to install'
    required: true
runs:
  using: "composite"
  steps:
    - name: Validate Inputs
      shell: bash
      run: |
        if [ -z "${{ inputs.python-version }}" ]; then
          echo "python-version is empty"
          exit 1
        fi 

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Qt (Windows)
      if: matrix.os == 'windows-latest'
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.9.1'
        arch: 'win64_msvc2022_64'

    - name: Install Qt (Linux/MacOS)
      if: matrix.os != 'windows-latest'
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.9.1'

    - name: Build
      shell: bash
      run: |
        pip install -v .[dev]

    - name: Test with unittest
      shell: bash
      run: python -m unittest discover -v -s tests
