[mypy]
disallow_untyped_defs = True
check_untyped_defs = True
warn_return_any = True
python_version = 3.11
mypy_path = $MYPY_CONFIG_FILE_DIR/src,$MYPY_CONFIG_FILE_DIR/src/builtin_plugins
packages = amulet_editor,amulet_team_3d_viewer,amulet_team_editor,amulet_team_inspector,amulet_team_level,amulet_team_resource_pack,amulet_team_selection,tablericons,thread_manager
