[build-system]
requires = [
    "setuptools >= 42",
    "wheel",
    "versioneer",
    "pybind11 ~= 2.12",
    "amulet_nbt ~= 4.0a2",
    "amulet_core == 2.0a7"
]
build-backend = "setuptools.build_meta"
