# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ${{ matrix.cfg.os }}
    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        cfg:
        - {os: windows-latest, python-version: '3.10', architecture: x64}
        - {os: macos-latest, python-version: '3.10', architecture: x64}
        - {os: ubuntu-latest, python-version: '3.10', architecture: x64}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.cfg.python-version }} ${{ matrix.cfg.architecture }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.cfg.python-version }}
        architecture: ${{ matrix.cfg.architecture }}

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install setuptools wheel twine pyinstaller~=5.6 build

    - name: Create Installer
      run: |
        pip install git+https://github.com/Amulet-Team/python-build-tool.git
        pip install -e --upgrade --upgrade-strategy eager .
        pbt freeze
        pbt installer

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: '*.*'
